server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://seminar-db.ccj1kt52lcn7.ap-northeast-2.rds.amazonaws.com:3306/seminarDB?useSSL=false&serverTimezone=UTC
    username: master
    password: seminardb
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update