server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://seminar-api.ccj1kt52lcn7.ap-northeast-2.rds.amazonaws.com:3306/seminarAPI?useSSL=false&serverTimezone=UTC
    username: master
    password: seminarapi
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: update
