version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: seminar2
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: seminar
      MYSQL_DATABASE: seminar
    volumes:
      - ./db:/var/lib/mysql